version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: install packages
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
workflows:
  Testing:
    jobs:
      - test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
